import Navbar from '@/components/navbar'
import Head from 'next/head'


export default function Home() {
  const navMenu = [
    { path: "/", menu: "Hompage" },
    { path: "/aboutus", menu: "About us" },
    { path: "/contactus", menu: "Contact us" },
    { path: "/Login", menu: "Login Now" },
  ]

  return (
    <>
      <Head>
        <title>Account Manager || Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar navMenu={navMenu} />

    </>
  )
}
